angular.module('myApp', [])
.controller('myAppController', function($scope) {
	$scope.tabs = [
		{ name: "Angular Tab 1", href: "#tab1c", css: "active" }, 
		{ name: "Angular Tab 2", href: "#tab2c" }, 
		{ name: "Angular Tab 3", href: "#tab3c" }, 
		{ name: "Angular Tab 4", href: "#tab4c" }, 
		{ name: "Angular Tab 5", href: "#tab5c" }, 
		{ name: "Angular Tab 6", href: "#tab6c" }, 
		{ name: "Angular Tab 7", href: "#tab7c" }, 
		{ name: "Angular Tab 8", href: "#tab8c" }, 
		{ name: "Angular Tab 9", href: "#tab9c" }, 
		{ name: "Angular Tab 10", href: "#tab10c" }, 
		{ name: "Angular Tab 11", href: "#tab11c" }, 
		{ name: "Angular Tab 12", href: "#tab12c" }, 
		{ name: "Angular Tab 13", href: "#tab13c" }, 
		{ name: "Angular Tab 14", href: "#tab14c" }, 
		{ name: "Angular Tab 15", href: "#tab15c" }, 
		{ name: "Angular Tab 16", href: "#tab16c" }, 
	];

	$scope.tabsContent = [
		{ id: "tab1c", content: "Angular Tab 1 Content", css: "active" },
		{ id: "tab2c", content: "Angular Tab 2 Content" },
		{ id: "tab3c", content: "Angular Tab 3 Content" },
		{ id: "tab4c", content: "Angular Tab 4 Content" },
		{ id: "tab5c", content: "Angular Tab 5 Content" },
		{ id: "tab6c", content: "Angular Tab 6 Content" },
		{ id: "tab7c", content: "Angular Tab 7 Content" },
		{ id: "tab8c", content: "Angular Tab 8 Content" },
		{ id: "tab9c", content: "Angular Tab 9 Content" },
		{ id: "tab10c", content: "Angular Tab 10 Content" },
		{ id: "tab11c", content: "Angular Tab 11 Content" },
		{ id: "tab12c", content: "Angular Tab 12 Content" },
		{ id: "tab13c", content: "Angular Tab 13 Content" },
		{ id: "tab14c", content: "Angular Tab 14 Content" },
		{ id: "tab15c", content: "Angular Tab 15 Content" },
		{ id: "tab16c", content: "Angular Tab 16 Content" },
	]
	$scope.bootstrapTabs = [
		{ name: "Angular Tab 1", href: "#tab1d", css: "active" }, 
		{ name: "Angular Tab 2", href: "#tab2d" }, 
		{ name: "Angular Tab 3", href: "#tab3d" }, 
		{ name: "Angular Tab 4", href: "#tab4d" }, 
		{ name: "Angular Tab 5", href: "#tab5d" }, 
		{ name: "Angular Tab 6", href: "#tab6d" }, 
		{ name: "Angular Tab 7", href: "#tab7d" }, 
		{ name: "Angular Tab 8", href: "#tab8d" }, 
		{ name: "Angular Tab 9", href: "#tab9d" }, 
		{ name: "Angular Tab 10", href: "#tab10d" }, 
		{ name: "Angular Tab 11", href: "#tab11d" }, 
		{ name: "Angular Tab 12", href: "#tab12d" }, 
		{ name: "Angular Tab 13", href: "#tab13d" }, 
		{ name: "Angular Tab 14", href: "#tab14d" }, 
		{ name: "Angular Tab 15", href: "#tab15d" }, 
		{ name: "Angular Tab 16", href: "#tab16d" }, 
	];

	$scope.bootstrapTabsContent = [
		{ id: "tab1d", content: "Angular Tab 1 Content", css: "active" },
		{ id: "tab2d", content: "Angular Tab 2 Content" },
		{ id: "tab3d", content: "Angular Tab 3 Content" },
		{ id: "tab4d", content: "Angular Tab 4 Content" },
		{ id: "tab5d", content: "Angular Tab 5 Content" },
		{ id: "tab6d", content: "Angular Tab 6 Content" },
		{ id: "tab7d", content: "Angular Tab 7 Content" },
		{ id: "tab8d", content: "Angular Tab 8 Content" },
		{ id: "tab9d", content: "Angular Tab 9 Content" },
		{ id: "tab10d", content: "Angular Tab 10 Content" },
		{ id: "tab11d", content: "Angular Tab 11 Content" },
		{ id: "tab12d", content: "Angular Tab 12 Content" },
		{ id: "tab13d", content: "Angular Tab 13 Content" },
		{ id: "tab14d", content: "Angular Tab 14 Content" },
		{ id: "tab15d", content: "Angular Tab 15 Content" },
		{ id: "tab16d", content: "Angular Tab 16 Content" },
	]
});